# Generated by Django 4.2.17 on 2025-01-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_post_options_post_updated_on_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'permissions': [('can_create_post', 'Can create post')]},
        ),
    ]
