# Generated by Django 4.2.17 on 2025-01-20 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_collaboraterequest_excerpt_collaboraterequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboraterequest',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='banner',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
