# Generated by Django 4.2.17 on 2025-01-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_alter_collaboraterequest_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
