# Generated by Django 4.2.17 on 2025-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
