# Generated by Django 4.2.17 on 2025-01-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
